defaults:
  - dataset: default
  - optim: default
  - _self_

hf_model: Qwen/Qwen2.5-7B
logdir: logs/result
checkpoint: ${logdir}/state_dict.pt
quantize_bits: 16

samples:
  train:
    backbone: 1
    last_layer: 1
  test:
    backbone: 1
    last_layer: 1

n_eval_trials: 1
gpu_id: 0
seed: 0

wandb:
  project: bayesadapt
  name: run
