defaults:
  - dataset@train_dataset: winogrande_s
  - dataset@test_dataset: ${dataset@train_dataset}
  - optim: default
  - trainer: default
  - collate_fn: base
  - _self_

log_root: logs
hf_model: Qwen/Qwen2.5-7B
checkpoint: null
load_pretrained_checkpoint: false
quantize_bits: 16
overwrite: false

pbar: true

use_wandb: true


samples:
  train:
    backbone: 1
    last_layer: 1
  test:
    backbone: 1
    last_layer: 1

n_eval_trials: 1
gpu_id: 0
seed: 0

wandb:
  project: bayesadapt
  name: run
