defaults:
  - default #root default
  - lora: default
  - lora/wrapper: scalabl
  - _self_
  - override optim: vi

optim:
  kl_optimizer:
    lr: 0.2

n_test_samples: 10
n_eval_trials: 5

#lora:
  #wrapper:
    #_partial_: true
    #_target_: lorawrappers.ScalablLoraWrapper
    #eps: 0.05
