defaults:
  - default #conf/default.yaml
  - lora: default
  - lora/wrapper: blob
  - _self_
  - override optim: vi

optim:
  kl_optimizer:
    lr: 0.01

samples:
  train:
    backbone: 1
    last_layer: 1
  test:
    backbone: 1
    last_layer: 10

lora:
  wrapper:
    target_modules:
      - lm_head

n_eval_trials: 5
