defaults:
  - default #conf/default.yaml
  - lora: default
  - lora/wrapper: blob
  - _self_
  - override optim: vi

optim:
  kl_optimizer:
    lr: 0.01

samples:
  train:
    backbone: 1
    last_layer: 1
  test:
    backbone: 10
    last_layer: 1

n_eval_trials: 5

#lora:
  #wrapper:
    #_partial_: true
    #_target_: lorawrappers.BlobLoraWrapper
    #bayes_eps: 0.05
    #bayes_beta: 0.2
