defaults:
  - default #conf/default.yaml
  - lora: default
  - lora/wrapper: deepensemble
  - _self_

samples:
  train:
    backbone: ${lora.wrapper.ensemble_size}
    last_layer: ${lora.wrapper.ensemble_size}
  test:
    backbone: ${lora.wrapper.ensemble_size}
    last_layer: ${lora.wrapper.ensemble_size}

n_eval_trials: 1
