defaults:
  - default #conf/default.yaml
  - lora: default
  - lora/wrapper: mcdropout
  - _self_

lora:
  config:
    lora_dropout: 0.1

samples:
  train:
    backbone: 1
    last_layer: 1
  test:
    backbone: 10
    last_layer: 1


n_eval_trials: 5
