defaults:
  - default #conf/default.yaml
  - lora: default
  - lora/wrapper: deepensemble
  - _self_

n_train_samples: ${lora.wrapper.ensemble_size}
n_test_samples: ${lora.wrapper.ensemble_size}

#lora:
  #wrapper:
    #_partial_: true
    #_target_: lorawrappers.BlobLoraWrapper
    #bayes_eps: 0.05
    #bayes_beta: 0.2
