config:
  _target_: peft.LoraConfig
  task_type: CAUSAL_LM
  inference_mode: false
  r: 8
  lora_alpha: 16
  lora_dropout: 0.0
  target_modules: 
    - lm_head
    - q_proj
    - v_proj

wrapper: null
